<?php

namespace App\Exports;

use App\Models\CaseReportForm;
use Carbon\Carbon;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;

class CaseReportFormExport implements FromQuery, WithHeadings, WithMapping
{

    use Exportable;
    private $row = 0;
    public function query()
    {
        return CaseReportForm::query();
    }

    public function headings(): array
    {

        return [

            '#',
            'Protocol Number',
            'Date of Consent',
            'UHID',
            'DOB',
            'Age',
            'Gender',

            'Height',
            'Weight',
            'Body Surface Area',
            'Heart Rate',
            'Systolic BP',
            'Diastolic BP',

            'Angina on Exertion', 'Class', 'Duration',
            'Dyspnea on Exertion', 'Class', 'Duration',
            'Syncope', 'Class', 'Duration',
            'Palpitation', 'Class', 'Duration',
            'Giddiness', 'Class', 'Duration',
            'Fever', 'Class', 'Duration',
            'Heart Failure Admission', 'Class', 'Duration',
            'Others', 'Others Specify', 'Duration',

            'Smoking', 'Quantity', 'Since', 'Stopped',
            'Drinking', 'Quantity', 'Since', 'Stopped',
            'Tobacco', 'Quantity', 'Since', 'Stopped',

            'Date of Investigation',
            'Red Blood Cell (RBC)',
            'White Blood Cell (WBC)',
            'Hemoglobin',
            'Hematocrit',
            'Platelet Count',
            'Blood Urea',
            'Serum Creatinine',
            'Alanine Transaminase (ALT)',
            'Aspartate Transaminase (AST)',
            'Alkaline Phosphatase (ALP)',
            'Albumin',
            'Total Protein',
            'Bilirubin',
            'Prothrombin Time(PT) INR',

            'Date of Investigation',
            'Rhythm',
            'Others',
            'Rate',
            'LVH',
            'LV Strain',
            'PR Interval',
            'QRS Duration',

            'Date of Investigation',
            'Peak Velocity',
            'Velocity Time Integral(Aortic Valve)',
            'Peak Gradient',
            'Mean Gradient',
            'Heart Rate',
            'Stroke Volume',
            'DVI',
            'Effective Orifice Area (EOA)',
            'Acceleration Time',
            'LVOT VTI',
            'LV Mass',
            'IVS Diastole',
            'PW Diastole',
            'LVID-End Systole',
            'LVID-End Diastole',
            'Ejection Fraction',

            'Date of Review',
            'Peak Velocity', 'Normality', 'Abnormal',
            'Velocity Time Integral(Aortic Valve)', 'Normality', 'Abnormal',
            'Peak Gradient', 'Normality', 'Abnormal',
            'Mean Gradient', 'Normality', 'Abnormal',
            'Heart Rate', 'Normality', 'Abnormal',
            'Stroke Volume', 'Normality', 'Abnormal',
            'DVI', 'Normality', 'Abnormal',
            'Effective Orifice Area (EOA)', 'Normality', 'Abnormal',
            'Acceleration Time', 'Normality', 'Abnormal',
            'LVOT VTI', 'Normality', 'Abnormal',
            'LV Mass', 'Normality', 'Abnormal',
            'IVS Diastole', 'Normality', 'Abnormal',
            'PW Diastole', 'Normality', 'Abnormal',
            'LVID-End Systole', 'Normality', 'Abnormal',
            'LVID-End Diastole', 'Normality', 'Abnormal',
            'Ejection Fraction', 'Normality', 'Abnormal',

            'Date of Procedure',
            'Arterial Cannulation',
            'Venous Cannulation',
            'Cardioplegia',
            'Aortotomy', 'Others',
            'Annular Suturing Technique', 'Others',
            'Total Cardiopulmonary Bypass Time',
            'Aortic Cross Clamp Time',
            'Concomitant Procedure',
            'All Paravalvular Leak', 'If Yes, specify',
            'Major Paravalvular Leak', 'If Yes, specify',

            'Heart Rate',
            'Systolic BP',
            'Diastolic BP',

            'Angina on Exertion', 'Class', 'Duration',
            'Dyspnea on Exertion', 'Class', 'Duration',
            'Syncope', 'Class', 'Duration',
            'Palpitation', 'Class', 'Duration',
            'Giddiness', 'Class', 'Duration',
            'Fever', 'Class', 'Duration',
            'Heart Failure Admission', 'Class', 'Duration',
            'Others', 'Others Specify', 'Duration',

            'Date of Investigation',
            'Red Blood Cell (RBC)',
            'White Blood Cell (WBC)',
            'Hemoglobin',
            'Hematocrit',
            'Platelet Count',
            'Blood Urea',
            'Serum Creatinine',
            'Alanine Transaminase (ALT)',
            'Aspartate Transaminase (AST)',
            'Alkaline Phosphatase (ALP)',
            'Albumin',
            'Total Protein',
            'Bilirubin',
            'Prothrombin Time(PT) INR',

            'Date of Investigation',
            'Rhythm',
            'Others',
            'Rate',
            'LVH',
            'LV Strain',
            'PR Interval',
            'QRS Duration',

            'Date of Investigation',
            'Peak Velocity',
            'Velocity Time Integral(Aortic Valve)',
            'Peak Gradient',
            'Mean Gradient',
            'Heart Rate',
            'Stroke Volume',
            'DVI',
            'Effective Orifice Area (EOA)',
            'Acceleration Time',
            'LVOT VTI',
            'LV Mass',
            'IVS Diastole',
            'PW Diastole',
            'LVID-End Systole',
            'LVID-End Diastole',
            'Ejection Fraction',

            'Date of Review',
            'Peak Velocity', 'Normality', 'Abnormal',
            'Velocity Time Integral(Aortic Valve)', 'Normality', 'Abnormal',
            'Peak Gradient', 'Normality', 'Abnormal',
            'Mean Gradient', 'Normality', 'Abnormal',
            'Heart Rate', 'Normality', 'Abnormal',
            'Stroke Volume', 'Normality', 'Abnormal',
            'DVI', 'Normality', 'Abnormal',
            'Effective Orifice Area (EOA)', 'Normality', 'Abnormal',
            'Acceleration Time', 'Normality', 'Abnormal',
            'LVOT VTI', 'Normality', 'Abnormal',
            'LV Mass', 'Normality', 'Abnormal',
            'IVS Diastole', 'Normality', 'Abnormal',
            'PW Diastole', 'Normality', 'Abnormal',
            'LVID-End Systole', 'Normality', 'Abnormal',
            'LVID-End Diastole', 'Normality', 'Abnormal',
            'Ejection Fraction', 'Normality', 'Abnormal',

            'Structural valve deterioration', 'Date', 'Comments',
            'Valve Thrombosis', 'Date', 'Comments',
            'All Paravalvular Leak', 'Date', 'Comments',
            'Major Paravalvular Leak', 'Date', 'Comments',
            'Non-structural Valve Deterioration', 'Date', 'Comments',
            'Thromboembolism', 'Date', 'Comments',
            'All Bleeding/Hemorrhage', 'Date', 'Comments',
            'Major Bleeding/Hemorrhage', 'Date', 'Comments',
            'Endocarditis', 'Date', 'Comments',
            'All-cause Mortality', 'Date', 'Comments',
            'Valve-related Mortality', 'Date', 'Comments',
            'Valve-related reoperation', 'Date', 'Comments',
            'Explant','Haemolysis', 'Date', 'Comments',
            'Sudden Unexplained Death', 'Date', 'Comments',
            'Cardiac Death', 'Date', 'Comments',
        ];
    }

    public function map($crf): array
    {
        //    dd($crf->preoperatives->physicalexaminations->height);
        $preoperative = $crf->preoperatives;
        $intraoperative = $crf->intraoperatives;
        $postoperative = $crf->postoperatives;
        return [
            [
                ++$this->row,
                "2021-04",
                Carbon::parse($crf->date_of_consent)->format('d/m/Y'),
                $crf->uhid,
                Carbon::parse($crf->date_of_birth)->format('d/m/Y'),
                Carbon::createFromDate($crf->date_of_birth)->diffInYears(Carbon::now()),
                $crf->gender,
                $preoperative->physicalexaminations->height,
                $preoperative->physicalexaminations->weight,
                $preoperative->physicalexaminations->bsa,
                $preoperative->physicalexaminations->heart_rate,
                $preoperative->physicalexaminations->systolic_bp,
                $preoperative->physicalexaminations->diastolic_bp,

                $preoperative->symptoms->angina === 1 ? 'Yes' : 'No',
                $preoperative->symptoms->angina_class,
                $preoperative->symptoms->angina_duration,

                $preoperative->symptoms->dyspnea,
                $preoperative->symptoms->dyspnea_class,
                $preoperative->symptoms->dyspnea_duration,
                $preoperative->symptoms->syncope,
                $preoperative->symptoms->syncope_duration,
                $preoperative->symptoms->palpitation,
                $preoperative->symptoms->palpitation_duration,
                $preoperative->symptoms->giddiness,
                $preoperative->symptoms->giddiness_duration,
                $preoperative->symptoms->fever,
                $preoperative->symptoms->fever_duration,
                $preoperative->symptoms->heart_failure_admission,
                $preoperative->symptoms->heart_failure_admission_duration,
                $preoperative->symptoms->others,
                $preoperative->symptoms->others_text,
                $preoperative->symptoms->others_duration,


                $preoperative->personalhistories->smoking,
                $preoperative->personalhistories->cigarettes,
                $preoperative->personalhistories->smoking_since,
                $preoperative->personalhistories->smoking_stopped,
                $preoperative->personalhistories->alchohol,
                $preoperative->personalhistories->quantity,
                $preoperative->personalhistories->alchohol_since,
                $preoperative->personalhistories->alchohol_stopped,
                $preoperative->personalhistories->tobacco,
                $preoperative->personalhistories->tobacco_type,
                $preoperative->personalhistories->tobacco_quantity,
                $preoperative->personalhistories->tobacco_since,
                $preoperative->personalhistories->tobacco_stopped,

                $preoperative->labinvestigations->li_date,
                $preoperative->labinvestigations->rbc,
                $preoperative->labinvestigations->wbc,
                $preoperative->labinvestigations->hemoglobin,
                $preoperative->labinvestigations->hematocrit,
                $preoperative->labinvestigations->platelet,
                $preoperative->labinvestigations->blood_urea,
                $preoperative->labinvestigations->serum_creatinine,
                $preoperative->labinvestigations->alt,
                $preoperative->labinvestigations->ast,
                $preoperative->labinvestigations->alp,
                $preoperative->labinvestigations->albumin,
                $preoperative->labinvestigations->total_protein,
                $preoperative->labinvestigations->bilirubin,
                $preoperative->labinvestigations->pt_inr,

                $preoperative->electrocardiograms->ecg_date ?? 'NA',
                $preoperative->electrocardiograms->rhythm,
                $preoperative->electrocardiograms->rhythm_others,
                $preoperative->electrocardiograms->rate,
                $preoperative->electrocardiograms->lvh,
                $preoperative->electrocardiograms->lvs,
                $preoperative->electrocardiograms->printerval,
                $preoperative->electrocardiograms->qrsduration,

                $preoperative->echocardiographies->echodate  ?? 'NA',
                $preoperative->echocardiographies->peak_velocity,
                $preoperative->echocardiographies->velocity_time_integral,
                $preoperative->echocardiographies->peak_gradient,
                $preoperative->echocardiographies->mean_gradient,
                $preoperative->echocardiographies->heart_rate,
                $preoperative->echocardiographies->stroke_volume,
                $preoperative->echocardiographies->dvi,
                $preoperative->echocardiographies->eoa,
                $preoperative->echocardiographies->acceleration_time,
                $preoperative->echocardiographies->lvot_vti,
                $preoperative->echocardiographies->lv_mass,
                $preoperative->echocardiographies->ivs_diastole,
                $preoperative->echocardiographies->pw_diastole,
                $preoperative->echocardiographies->lvidend_systole,
                $preoperative->echocardiographies->lvidend_diastole,
                $preoperative->echocardiographies->ejection_fraction,

                $preoperative->echocardiographies->r_echodate  ?? 'NA',

                $preoperative->echocardiographies->r_peak_velocity,
                $preoperative->echocardiographies->peak_velocity_normality,
                $preoperative->echocardiographies->peak_velocity_abnormality,

                $preoperative->echocardiographies->r_velocity_time_integral,
                $preoperative->echocardiographies->velocity_time_integral_normality,
                $preoperative->echocardiographies->velocity_time_integral_abnormality,

                $preoperative->echocardiographies->r_peak_gradient,
                $preoperative->echocardiographies->peak_gradient_normality,
                $preoperative->echocardiographies->peak_gradient_abnormality,

                $preoperative->echocardiographies->r_mean_gradient,
                $preoperative->echocardiographies->mean_gradient_normality,
                $preoperative->echocardiographies->mean_gradient_abnormality,

                $preoperative->echocardiographies->r_heart_rate,
                $preoperative->echocardiographies->heart_rate_normality,
                $preoperative->echocardiographies->heart_rate_abnormality,

                $preoperative->echocardiographies->r_stroke_volume,
                $preoperative->echocardiographies->stroke_volume_normality,
                $preoperative->echocardiographies->stroke_volume_abnormality,

                $preoperative->echocardiographies->r_dvi,
                $preoperative->echocardiographies->dvi_normality,
                $preoperative->echocardiographies->dvi_abnormality,

                $preoperative->echocardiographies->r_eoa,
                $preoperative->echocardiographies->eoa_normality,
                $preoperative->echocardiographies->eoa_abnormality,

                $preoperative->echocardiographies->r_acceleration_time,
                $preoperative->echocardiographies->acceleration_time_normality,
                $preoperative->echocardiographies->acceleration_time_abnormality,

                $preoperative->echocardiographies->r_lvot_vti,
                $preoperative->echocardiographies->lvot_vti_normality,
                $preoperative->echocardiographies->lvot_vti_abnormality,

                $preoperative->echocardiographies->r_lv_mass,
                $preoperative->echocardiographies->lv_mass_normality,
                $preoperative->echocardiographies->lv_mass_abnormality,

                $preoperative->echocardiographies->r_ivs_diastole,
                $preoperative->echocardiographies->ivs_diastole_normality,
                $preoperative->echocardiographies->ivs_diastole_abnormality,

                $preoperative->echocardiographies->r_pw_diastole,
                $preoperative->echocardiographies->pw_diastole_normality,
                $preoperative->echocardiographies->pw_diastole_abnormality,

                $preoperative->echocardiographies->r_lvidend_systole,
                $preoperative->echocardiographies->lvidend_systole_normality,
                $preoperative->echocardiographies->lvidend_systole_abnormality,

                $preoperative->echocardiographies->r_lvidend_diastole,
                $preoperative->echocardiographies->lvidend_diastole_normality,
                $preoperative->echocardiographies->lvidend_diastole_abnormality,

                $preoperative->echocardiographies->r_ejection_fraction,
                $preoperative->echocardiographies->ejection_fraction_normality,
                $preoperative->echocardiographies->ejection_fraction_abnormality,




                $intraoperative->date_of_procedure,
                $intraoperative->arterial_cannulation,
                $intraoperative->venous_cannulation,
                $intraoperative->cardioplegia,
                $intraoperative->aortotomy,
                $intraoperative->aortotomy_others,
                $intraoperative->annular_suturing_technique,
                $intraoperative->annular_suturing_others,
                $intraoperative->tcb_time,
                $intraoperative->acc_time,
                $intraoperative->concomitant_procedure,
                $intraoperative->all_paravalvular_leak,
                $intraoperative->all_paravalvular_leak_specify,
                $intraoperative->major_paravalvular_leak,
                $intraoperative->major_paravalvular_leak_specify,

                $postoperative->physicalexaminations->heart_rate,
                $postoperative->physicalexaminations->systolic_bp,
                $postoperative->physicalexaminations->diastolic_bp,

                $postoperative->symptoms->angina === 1 ? 'Yes' : 'No',
                $postoperative->symptoms->angina_class,
                $postoperative->symptoms->angina_duration,

                $postoperative->symptoms->dyspnea,
                $postoperative->symptoms->dyspnea_class,
                $postoperative->symptoms->dyspnea_duration,
                $postoperative->symptoms->syncope,
                $postoperative->symptoms->syncope_duration,
                $postoperative->symptoms->palpitation,
                $postoperative->symptoms->palpitation_duration,
                $postoperative->symptoms->giddiness,
                $postoperative->symptoms->giddiness_duration,
                $postoperative->symptoms->fever,
                $postoperative->symptoms->fever_duration,
                $postoperative->symptoms->heart_failure_admission,
                $postoperative->symptoms->heart_failure_admission_duration,
                $postoperative->symptoms->others,
                $postoperative->symptoms->others_text,
                $postoperative->symptoms->others_duration,



                $postoperative->labinvestigations->li_date,
                $postoperative->labinvestigations->rbc,
                $postoperative->labinvestigations->wbc,
                $postoperative->labinvestigations->hemoglobin,
                $postoperative->labinvestigations->hematocrit,
                $postoperative->labinvestigations->platelet,
                $postoperative->labinvestigations->blood_urea,
                $postoperative->labinvestigations->serum_creatinine,
                $postoperative->labinvestigations->alt,
                $postoperative->labinvestigations->ast,
                $postoperative->labinvestigations->alp,
                $postoperative->labinvestigations->albumin,
                $postoperative->labinvestigations->total_protein,
                $postoperative->labinvestigations->bilirubin,
                $postoperative->labinvestigations->pt_inr,

                $postoperative->electrocardiograms->ecg_date,
                $postoperative->electrocardiograms->rhythm,
                $postoperative->electrocardiograms->rhythm_others,
                $postoperative->electrocardiograms->rate,
                $postoperative->electrocardiograms->lvh,
                $postoperative->electrocardiograms->lvs,
                $postoperative->electrocardiograms->printerval,
                $postoperative->electrocardiograms->qrsduration,

                $postoperative->echocardiographies->echodate,
                $postoperative->echocardiographies->peak_velocity,
                $postoperative->echocardiographies->velocity_time_integral,
                $postoperative->echocardiographies->peak_gradient,
                $postoperative->echocardiographies->mean_gradient,
                $postoperative->echocardiographies->heart_rate,
                $postoperative->echocardiographies->stroke_volume,
                $postoperative->echocardiographies->dvi,
                $postoperative->echocardiographies->eoa,
                $postoperative->echocardiographies->acceleration_time,
                $postoperative->echocardiographies->lvot_vti,
                $postoperative->echocardiographies->lv_mass,
                $postoperative->echocardiographies->ivs_diastole,
                $postoperative->echocardiographies->pw_diastole,
                $postoperative->echocardiographies->lvidend_systole,
                $postoperative->echocardiographies->lvidend_diastole,
                $postoperative->echocardiographies->ejection_fraction,

                $postoperative->echocardiographies->r_echodate,
                $postoperative->echocardiographies->r_peak_velocity,
                $postoperative->echocardiographies->peak_velocity_normality,
                $postoperative->echocardiographies->peak_velocity_abnormality,

                $postoperative->echocardiographies->r_velocity_time_integral,
                $postoperative->echocardiographies->velocity_time_integral_normality,
                $postoperative->echocardiographies->velocity_time_integral_abnormality,

                $postoperative->echocardiographies->r_peak_gradient,
                $postoperative->echocardiographies->peak_gradient_normality,
                $postoperative->echocardiographies->peak_gradient_abnormality,

                $postoperative->echocardiographies->r_mean_gradient,
                $postoperative->echocardiographies->mean_gradient_normality,
                $postoperative->echocardiographies->mean_gradient_abnormality,

                $postoperative->echocardiographies->r_heart_rate,
                $postoperative->echocardiographies->heart_rate_normality,
                $postoperative->echocardiographies->heart_rate_abnormality,

                $postoperative->echocardiographies->r_stroke_volume,
                $postoperative->echocardiographies->stroke_volume_normality,
                $postoperative->echocardiographies->stroke_volume_abnormality,

                $postoperative->echocardiographies->r_dvi,
                $postoperative->echocardiographies->dvi_normality,
                $postoperative->echocardiographies->dvi_abnormality,

                $postoperative->echocardiographies->r_eoa,
                $postoperative->echocardiographies->eoa_normality,
                $postoperative->echocardiographies->eoa_abnormality,

                $postoperative->echocardiographies->r_acceleration_time,
                $postoperative->echocardiographies->acceleration_time_normality,
                $postoperative->echocardiographies->acceleration_time_abnormality,

                $postoperative->echocardiographies->r_lvot_vti,
                $postoperative->echocardiographies->lvot_vti_normality,
                $postoperative->echocardiographies->lvot_vti_abnormality,

                $postoperative->echocardiographies->r_lv_mass,
                $postoperative->echocardiographies->lv_mass_normality,
                $postoperative->echocardiographies->lv_mass_abnormality,

                $postoperative->echocardiographies->r_ivs_diastole,
                $postoperative->echocardiographies->ivs_diastole_normality,
                $postoperative->echocardiographies->ivs_diastole_abnormality,

                $postoperative->echocardiographies->r_pw_diastole,
                $postoperative->echocardiographies->pw_diastole_normality,
                $postoperative->echocardiographies->pw_diastole_abnormality,

                $postoperative->echocardiographies->r_lvidend_systole,
                $postoperative->echocardiographies->lvidend_systole_normality,
                $postoperative->echocardiographies->lvidend_systole_abnormality,

                $postoperative->echocardiographies->r_lvidend_diastole,
                $postoperative->echocardiographies->lvidend_diastole_normality,
                $postoperative->echocardiographies->lvidend_diastole_abnormality,

                $postoperative->echocardiographies->r_ejection_fraction,
                $postoperative->echocardiographies->ejection_fraction_normality,
                $postoperative->echocardiographies->ejection_fraction_abnormality,

                $postoperative->safetyparameters->has_structural_value_deterioration,
                $postoperative->safetyparameters->date_structural_value_deterioration,
                $postoperative->safetyparameters->structural_value_deterioration,
                $postoperative->safetyparameters->has_valve_thrombosis,
                $postoperative->safetyparameters->date_valve_thrombosis,
                $postoperative->safetyparameters->valve_thrombosis,
                $postoperative->safetyparameters->has_all_paravalvular_leak,
                $postoperative->safetyparameters->date_all_paravalvular_leak,
                $postoperative->safetyparameters->all_paravalvular_leak,
                $postoperative->safetyparameters->has_major_paravalvular_leak,
                $postoperative->safetyparameters->date_major_paravalvular_leak,
                $postoperative->safetyparameters->major_paravalvular_leak,
                $postoperative->safetyparameters->has_non_structural_value_deterioration,
                $postoperative->safetyparameters->date_non_structural_value_deterioration,
                $postoperative->safetyparameters->non_structural_value_deterioration,
                $postoperative->safetyparameters->has_thromboembolism,
                $postoperative->safetyparameters->date_thromboembolism,
                $postoperative->safetyparameters->thromboembolism,
                $postoperative->safetyparameters->has_all_bleeding,
                $postoperative->safetyparameters->date_all_bleeding,
                $postoperative->safetyparameters->all_bleeding,
                $postoperative->safetyparameters->has_major_bleeding,
                $postoperative->safetyparameters->date_major_bleeding,
                $postoperative->safetyparameters->major_bleeding,
                $postoperative->safetyparameters->has_endocarditis,
                $postoperative->safetyparameters->date_endocarditis,
                $postoperative->safetyparameters->endocarditis,
                $postoperative->safetyparameters->has_all_mortality,
                $postoperative->safetyparameters->date_all_mortality,
                $postoperative->safetyparameters->all_mortality,
                $postoperative->safetyparameters->has_valve_mortality,
                $postoperative->safetyparameters->date_valve_mortality,
                $postoperative->safetyparameters->valve_mortality,
                $postoperative->safetyparameters->has_valve_related_operation,
                $postoperative->safetyparameters->date_valve_related_operation,
                $postoperative->safetyparameters->valve_related_operation,
                $postoperative->safetyparameters->has_explant,
                $postoperative->safetyparameters->date_explant,
                $postoperative->safetyparameters->explant,
                $postoperative->safetyparameters->has_haemolysis,
                $postoperative->safetyparameters->date_haemolysis,
                $postoperative->safetyparameters->haemolysis,
                $postoperative->safetyparameters->has_sudden_unexplained_death,
                $postoperative->safetyparameters->date_sudden_unexplained_death,
                $postoperative->safetyparameters->sudden_unexplained_death,
                $postoperative->safetyparameters->has_cardiac_death,
                $postoperative->safetyparameters->date_cardiac_death,
                $postoperative->safetyparameters->cardiac_death,


            ],

        ];
    }
}
